name: egu25
channels:
  - conda-forge
dependencies:
  - xarray=2025.3.0
  - ipyleaflet
  - scikit-learn
  - folium
  - graphviz
  - mapclassify
  - matplotlib=3.10.0
  - matplotlib-inline=0.1.7
  - bottleneck=1.4.2
  - fsspec
  - numpy=1.26.4
  - mystmd
  - cartopy
  - jupyter_server
  - pre-commit
  - black-jupyter
  - ipykernel
  - pooch
  - h5netcdf
  - netCDF4
  - kerchunk
  - graphviz
  - s3fs
  - pip
  - zarr>=3.0.6
  - dask
  - hvplot
  - dask-gateway
  - jupyter-book
  - jupyterlab-myst
